server:
  port: 8766
spring:
  application:
    name: customer-feign
  boot:
    admin:
      url: http://localhost:9999
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka
feign:
  hystrix:
    enabled: true
info:
  app:
   name: "@project.name@"  #从pom.xml中获取,pom.xml中需build中加入插件spring-boot-maven-plugin
   description: "@project.description@"
   version: "@project.version@"
   spring-boot-version: "@project.parent.version@"
